/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hivemind;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {
        System.out.println(Arrays.toString(args));
        System.out.print("Launching..");
        try {
            Startup.start(args);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
